FROM node:20-alpine AS frontend

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn config set registry https://registry.npmmirror.com && \
    yarn install --frozen-lockfile

COPY postcss.config.js tsconfig.build.json tsconfig.json webpack.config.ts ./
COPY tools/*Plugin.ts ./tools/

COPY resources ./resources

RUN yarn build && \
    cp resources/assets/src/images/bg.webp public/app/ && \
    cp resources/assets/src/images/favicon.ico public/app/ && \
    rm -rf *.config.js *.config.ts tsconfig.* \
      package.json yarn.lock node_modules/ \
      resources/assets/ resources/lang resources/misc resources/misc/backgrounds/ \
      tools/

FROM composer:latest AS vendor

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer config -g repos.packagist composer https://mirrors.aliyun.com/composer/ && \
    composer install \
    --prefer-dist \
    --no-dev \
    --no-suggest \
    --no-progress \
    --no-autoloader \
    --no-scripts \
    --no-interaction \
    --ignore-platform-reqs

FROM composer:latest AS builder

WORKDIR /app

COPY . ./

COPY --from=vendor /app ./
COPY --from=frontend /app/public ./public
COPY --from=frontend /app/resources/views/assets ./resources/views/assets

RUN mkdir -p storage/plugins storage/framework/views storage/framework/cache storage/logs plugins && \
    cp .env.example .env && \
    sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env && \
    sed -i 's/DB_DATABASE=blessingskin/DB_DATABASE=\/app\/storage\/database.db/' .env && \
    sed -i 's/PLUGINS_DIR=null/PLUGINS_DIR=\/app\/storage\/plugins/' .env && \
    composer dump-autoload -o --no-dev -n && \
    php artisan key:generate && \
    mv .env storage/ && \
    ln -s storage/.env .env && \
    touch storage/install.lock && \
    rm -rf *.config.js *.config.ts tsconfig.* \
      package.json yarn.lock node_modules/ \
      resources/assets/ resources/misc resources/misc/backgrounds/ \
      tools/

FROM php:8.2-apache

COPY docker/sources.list /etc/apt/sources.list.d/tencent.list
RUN rm -f /etc/apt/sources.list.d/debian.sources && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        libzip-dev \
        default-mysql-client \
        libmagickwand-dev \
        zip \
        unzip && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install -j$(nproc) gd zip pdo_mysql && \
    printf "\n" | pecl install imagick && \
    docker-php-ext-enable imagick && \
    rm -rf /var/lib/apt/lists/* /tmp/pear

WORKDIR /app

COPY --from=builder /app ./

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV APACHE_DOCUMENT_ROOT /app/public
RUN chown -R www-data:www-data . && \
    sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf && \
    sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf && \
    a2enmod rewrite headers

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]

VOLUME ["/app/storage"]
