export default {
  admin: {
    players: {
      delete: (player: number) => `/api/admin/players/${player}`,
      list: () => '/api/admin/players' as const,
      name: (player: number) => `/api/admin/players/${player}/name`,
      owner: (player: number) => `/api/admin/players/${player}/owner`,
      texture: (player: number) => `/api/admin/players/${player}/textures`,
    },
    users: {
      delete: (user: number) => `/api/admin/users/${user}`,
      email: (user: number) => `/api/admin/users/${user}/email`,
      list: () => '/api/admin/users' as const,
      nickname: (user: number) => `/api/admin/users/${user}/nickname`,
      password: (user: number) => `/api/admin/users/${user}/password`,
      permission: (user: number) => `/api/admin/users/${user}/permission`,
      score: (user: number) => `/api/admin/users/${user}/score`,
      verification: (user: number) => `/api/admin/users/${user}/verification`,
    },
  },
  auth: {
    bind: () => '/auth/bind' as const,
    forgot: () => '/api/auth/forgot' as const,
    login: () => '/auth/login' as const,
    logout: () => '/api/auth/logout' as const,
    register: () => '/auth/register' as const,
    reset: (uid: number) => `/api/auth/reset/${uid}`,
    verify: (uid: number) => `/auth/verify/${uid}`,
  },
  skinlib: {
    home: () => '/api/skinlib/list' as const,
    info: (texture: number) => `/api/skinlib/info/${texture}`,
    list: () => '/api/skinlib/list' as const,
    show: (tid: number) => `/skinlib/show/${tid}`,
  },
  texture: {
    delete: (texture: number) => `/api/texture/${texture}`,
    info: (texture: number) => `/api/texture/${texture}`,
    name: (texture: number) => `/api/texture/${texture}/name`,
    privacy: (texture: number) => `/api/texture/${texture}/privacy`,
    type: (texture: number) => `/api/texture/${texture}/type`,
    upload: () => '/api/texture' as const,
  },
  user: {
    closet: {
      add: () => '/api/closet' as const,
      ids: () => '/api/user/closet/ids' as const,
      list: () => '/api/closet' as const,
      page: () => '/user/closet' as const,
      remove: (tid: number) => `/api/closet/${tid}`,
      rename: (tid: number) => `/api/closet/${tid}`,
    },
    home: () => '/user' as const,
    notification: (id: number) => `/api/user/notifications/${id}`,
    player: {
      add: () => '/api/players' as const,
      clear: (player: number) => `/api/players/${player}/textures`,
      delete: (player: number) => `/api/players/${player}`,
      list: () => '/api/players' as const,
      page: () => '/user/player' as const,
      rename: (player: number) => `/api/players/${player}/name`,
      set: (player: number) => `/api/players/${player}/textures`,
    },
    profile: { avatar: () => '/api/user/profile/avatar' as const },
    score: () => '/api/user/score-info' as const,
    sign: () => '/api/user/sign' as const,
  },
}
